# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'THNaverMapView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'NMapsMap'
  
  # Pods for THNaverMapView

  target 'THNaverMapViewTests' do
    inherit! :search_paths
    # Pods for testing 
  end

  target 'THNaverMapViewUITests' do
    # Pods for testing
  end

end
